services:
  node-app1:
    build: .
    container_name: node-app1
    expose:
      - "80"

  node-app2:
    build: .
    container_name: node-app2
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - node-app1
      - node-app2